### ISSUE TITLE
Timed out while waiting for message

### ISSUE THREAD

**Issue by antoniovj1** [Tigge/antfs-cli#133]
Hi, using antfs-cli with my garmin 910xt I get this error. What can it be?

```Console
[antonio@antonio-System ~]$ antfs-cli 
Driver available: [ \<class ant.base.driver.SerialDriver at 0x7f9f93718c80>, \<class ant.base.driver.USB2Driver at 0x7f9f934c5390>, \<class ant.base.driver.USB3Driver at 0x7f9f934c53f8> ]
 
- Using: ant.base.driver.USB2Driver
Request basic information...
  
Capabilities:  array('B', [8, 3, 0, 186, 54, 0])

Starting system...

Key done...

Searching...

Authenticating with Forerunner 910XT (3845761737)

 - Passkey: OK

Downloading 2 file(s)

Downloading 2015-04-20_20-43-00_4_254.fit: [                              ] ETA:[....                          ] ETA: 0:00:45Traceback (most recent call last):
  
File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 343, in main
    g.start()
 
 File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 217, in start
    self._main()

  File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 155, in _main
    self.on_transport(beacon)
 
 File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 231, in on_transport
    self.download_file(fileobject)

  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 268, in download_file
    data = self.download(fil.get_index(), AntFSCLI._get_progress_callback())

  File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 311, in download
    self._send_command(DownloadRequest(index, offset, True, crc))
 
 File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 195, in _send_command
    self._channel.send_burst_transfer(data)
 
 File "/usr/local/lib/python2.7/dist-packages/ant/easy/channel.py", line 119, in send_burst_transfer
    self.send_burst_transfer(data)

  File "/usr/local/lib/python2.7/dist-packages/ant/easy/channel.py", line 114, in send_burst_transfer
    self.wait_for_event([Message.Code.EVENT_TRANSFER_TX_START])

  File "/usr/local/lib/python2.7/dist-packages/ant/easy/channel.py", line 51, in wait_for_event
    return wait_for_event(ok_codes, self._node._events, self._node._event_cond)

  File "/usr/local/lib/python2.7/dist-packages/ant/easy/filter.py", line 72, in wait_for_event
    return wait_for_message(match, process, queue, condition)
 
 File "/usr/local/lib/python2.7/dist-packages/ant/easy/filter.py", line 61, in wait_for_message
    raise AntException("Timed out while waiting for message")

AntException: Timed out while waiting for message
Interrupted: Timed out while waiting for message
```

**Comment by LeftyAce** [comment]
This looks very similar to issue 132:  https://github.com/Tigge/antfs-cli/issues/132
Can you try deleting the authfile in ~/.config/antfs-cli/XXXXXX ? (where XXXXXX is the device serial number of your  garmin).

**Comment by antoniovj1** [comment]
Solved.
Sorry for taking so long to respond, you are right. 

Thanks
