### ISSUE TITLE
Interrupted: [Errno 13] Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by Bigjuergo** [Tigge/antfs-cli#134]
hi, i installed antf-cli on my linux mate rebecca as described, but i get follwoing error after i tryed to start the communication with my 910XT:

antfs-cli

Driver available: [<class ant.base.driver.SerialDriver at 0x7f6da4d1b460>, <class ant.base.driver.USB2Driver at 0x7f6da4d1bae0>, <class ant.base.driver.USB3Driver at 0x7f6da4d1bb48>]
- Using: ant.base.driver.USB3Driver
  Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 341, in main
    g = AntFSCLI(config_dir, args)
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 129, in **init**
    Application.**init**(self)
  File "build/bdist.linux-x86_64/egg/ant/fs/manager.py", line 104, in **init**
    self._node = Node()
  File "build/bdist.linux-x86_64/egg/ant/easy/node.py", line 56, in __init__
    self.ant = Ant()
  File "build/bdist.linux-x86_64/egg/ant/base/ant.py", line 68, in **init**
    self._driver.open()
  File "build/bdist.linux-x86_64/egg/ant/base/driver.py", line 175, in open
    if dev.is_kernel_driver_active(0):
  File "build/bdist.linux-x86_64/egg/usb/core.py", line 989, in is_kernel_driver_active
    self._ctx.managed_open()
  File "build/bdist.linux-x86_64/egg/usb/core.py", line 105, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 722, in open_device
    return _DeviceHandle(dev)
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 600, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
  USBError: [Errno 13] Access denied (insufficient permissions)
  Interrupted: [Errno 13] Access denied (insufficient permissions)

can you please help me? 
thank you!

**Comment by Tigge** [comment]
Looks like it is not allowed to access the USB device. Did the udev rules get installed correctly and what usb stick are you using?

**Comment by Tigge** [comment]
@Bigjuergo perhaps you can also try to restart after verifying that the udev rules where correctly installed.

**Comment by netwel** [comment]
Same error no 13 here. Using  original Garmin Ant+ usb
How do I verify udev rules? (sorry I'm bit of noob still)

[tim@amber antfs-cli-master]$ antfs-cli 
Driver available: [<class ant.base.driver.USB2Driver at 0x7ff5a1f0bf58>, <class ant.base.driver.USB3Driver at 0x7ff5a1ec1050>]
 - Using: ant.base.driver.USB2Driver
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 354, in main
    g = AntFSCLI(config_dir, args)
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 131, in __init__
    Application.__init__(self)
  File "build/bdist.linux-x86_64/egg/ant/fs/manager.py", line 104, in __init__
    self._node = Node()
  File "build/bdist.linux-x86_64/egg/ant/easy/node.py", line 56, in __init__
    self.ant = Ant()
  File "build/bdist.linux-x86_64/egg/ant/base/ant.py", line 68, in __init__
    self._driver.open()
  File "build/bdist.linux-x86_64/egg/ant/base/driver.py", line 175, in open
    if dev.is_kernel_driver_active(0):
  File "build/bdist.linux-x86_64/egg/usb/core.py", line 989, in is_kernel_driver_active
    self._ctx.managed_open()
  File "build/bdist.linux-x86_64/egg/usb/core.py", line 105, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 722, in open_device
    return _DeviceHandle(dev)
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 600, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "build/bdist.linux-x86_64/egg/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 13] Access denied (insufficient permissions)
Interrupted: [Errno 13] Access denied (insufficient permissions)

**Comment by Bigjuergo** [comment]
i reinstalled everthing from the beginning.
now it is working!
i made a tutorial and put it on youtube
search for "Fastest Garmin Forerunner download Watch Activities with ANT+ on Linux Systems Tutorial"
or use link
https://www.youtube.com/watch?v=gdt6eMO2yWM

**Comment by netwel** [comment]
Awesome, it's working now, thanks!!

**Comment by Echelon9** [comment]
@Tigge This issue can probably be closed now.

**Comment by Tigge** [comment]
@Echelon9 thx.
