### ISSUE TITLE
AntFSDownloadException: ('Download request failed: ', 2)

### ISSUE THREAD

**Issue by cork** [Tigge/antfs-cli#140]
Downloading session data from Garmin Swim fails with a cryptic "Download request failed: 2"

antfs-cli: r55.7c75e77-1
openant-git: r92.7ab46c6-1
pyusb: 1.0.0b2-2

```
$ antfs-cli 
Driver available: [<class ant.base.driver.USB2Driver at 0x7fc31bab6530>, <class ant.base.driver.USB3Driver at 0x7fc31bab6598>]
 - Using: ant.base.driver.USB3Driver
Request basic information...
  Capabilities:  array('B', [8, 8, 0, 186, 54, 0, 223])
Starting system...
Key done...
Searching...
Authenticating with GARMIN SWIM (3880804314)
 - Passkey: OK
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/antfs_cli/program.py", line 354, in main
    g.start()
  File "/usr/lib/python2.7/site-packages/ant/fs/manager.py", line 217, in start
    self._main()
  File "/usr/lib/python2.7/site-packages/ant/fs/manager.py", line 155, in _main
    self.on_transport(beacon)
  File "/usr/lib/python2.7/site-packages/antfs_cli/program.py", line 196, in on_transport
    result = self.set_time()
  File "/usr/lib/python2.7/site-packages/ant/fs/manager.py", line 349, in set_time
    result = self._get_commandpipe()
  File "/usr/lib/python2.7/site-packages/ant/fs/manager.py", line 228, in _get_commandpipe
    return ant.fs.commandpipe.parse(self.download(0xfffe))
  File "/usr/lib/python2.7/site-packages/ant/fs/manager.py", line 331, in download
    response._get_argument("response"))
AntFSDownloadException: ('Download request failed: ', 2)
 - Set time: Interrupted: ('Download request failed: ', 2)
```

**Comment by jbiblio** [comment]
Same here. I've played a bit around with manager.py, and tuned the while-loop with
```
elif response._get_argument("response") == DownloadResponse.Response.NOT_READABLE:
    _logger.debug("Skip not-readable data at index %d", index)
    break
```

Now the last lines in debug output are
```
Get command, t15, s0
parsing data array('B', [68, 137, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 4, 0, 0])
Skip not-readable data at index 65534
Run 5
Stoping ant.easy
Stoping ant.base
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
Ant runner stopped
```

I've tried to run antfs-cli several times as suggested in the other bug reports, but with no success.

**Comment by metalinjection** [comment]
Hi there,
I am new to GitHub. I have the same problem when I try to download my swimming data from today.
I tried it also a couple of times and also compared the "hotfix" from a previous issue with the current code but it was already in the code.

My system is on Mac OS 10.8 and the GARMIN swim has never been on the internet before.

Here is my output from the debug:
```
Driver available: [<class ant.base.driver.SerialDriver at 0x1076ec598>, <class ant.base.driver.USB2Driver at 0x1076ec8d8>, <class ant.base.driver.USB3Driver at 0x1076ec940>]
 - Using: ant.base.driver.USB3Driver
Request basic information...
  Capabilities:  array('B', [8, 8, 0, 186, 54, 0, 223])
Starting system...
Key done...
Searching...
Authenticating with GARMIN SWIM (3904102831)
 - Passkey: OK
 - Set time: Interrupted: ('Download request failed: ', 2)
```
And here is my screen capture from the terminal:
```
sh-3.2# antfs-cli  --debug > antfs-cli.log
USB Find device, vendor 0xfcf, product 0x1009
USB Config values:
 Config 1
  Interface 0, Alt 0
   Endpoint 129
   Endpoint 1
No kernel driver active
UBS Endpoint out: <usb.core.Endpoint object at 0x1077d9e90>, 1
UBS Endpoint in: <usb.core.Endpoint object at 0x1077d9ed0>, 129
Ant runner started
Write data: [a4 01 4a 00 ef]
Read data: [a4 01 6f 20 ea] (now have [a4 01 6f 20 ea] in buffer)
Write data: [a4 09 46 00 a8 a4 23 b9 f5 5e 63 c1 74]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 03 40 00 46 00 a1] (now have [a4 03 40 00 46 00 a1] in buffer)
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 70, array('B', [0]))])
 - response found (0, 70, array('B', [0]))
requesting message 0x54
Write data: [a4 02 4d 00 54 bf]
done requesting message 0x54
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 07 54 08 08 00 ba 36 00 df a4] (now have [a4 07 54 08 08 00 ba 36 00 df a4] in buffer)
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (None, 84, array('B', [8, 8, 0, 186, 54, 0, 223]))])
 - response found (None, 84, array('B', [8, 8, 0, 186, 54, 0, 223]))
Write data: [a4 03 42 00 00 00 e5]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 03 40 00 42 00 a5] (now have [a4 03 40 00 42 00 a5] in buffer)
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 66, array('B', [0]))])
 - response found (0, 66, array('B', [0]))
Write data: [a4 03 43 00 00 10 f4]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 03 40 00 43 00 a4] (now have [a4 03 40 00 43 00 a4] in buffer)
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 67, array('B', [0]))])
 - response found (0, 67, array('B', [0]))
Write data: [a4 02 44 00 ff 1d]
wait for message matching <function match at 0x107772f50>
Read data: [a4 03 40 00 44 00 a3] (now have [a4 03 40 00 44 00 a3] in buffer)
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 68, array('B', [0]))])
 - response found (0, 68, array('B', [0]))
Write data: [a4 02 45 00 32 d1]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 03 40 00 45 00 a2] (now have [a4 03 40 00 45 00 a2] in buffer)
 - could not find response matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 69, array('B', [0]))])
 - response found (0, 69, array('B', [0]))
Write data: [a4 03 49 00 53 00 bd]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x107772f50>
Read data: [a4 03 40 00 49 00 ae] (now have [a4 03 40 00 49 00 ae] in buffer)
looking for matching message in deque([(None, 111, array('B', [32])), (0, 73, array('B', [0]))])
 - response found (0, 73, array('B', [0]))
Write data: [a4 05 51 00 00 00 01 00 f1]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x107772f50>
Read data: [a4 03 40 00 51 00 b6] (now have [a4 03 40 00 51 00 b6] in buffer)
looking for matching message in deque([(None, 111, array('B', [32])), (0, 81, array('B', [0]))])
 - response found (0, 81, array('B', [0]))
Write data: [a4 01 4b 00 ee]
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x107772f50>
Read data: [a4 03 40 00 4b 00 ac] (now have [a4 03 40 00 4b 00 ac] in buffer)
looking for matching message in deque([(None, 111, array('B', [32])), (0, 75, array('B', [0]))])
 - response found (0, 75, array('B', [0]))
Link level
<class 'usb.core.USBError'>, (60, 'Operation timed out')
<class 'usb.core.USBError'>, (60, 'Operation timed out')
<class 'usb.core.USBError'>, (60, 'Operation timed out')
<class 'usb.core.USBError'>, (60, 'Operation timed out')
<class 'usb.core.USBError'>, (60, 'Operation timed out')
Read data: [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] (now have [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] in buffer)
on link, 67035, (1499, 1)
requesting message 0x51
Write data: [a4 02 4d 00 51 ba]
done requesting message 0x51
wait for message matching <function match at 0x107772f50>
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x107772f50>
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 05 51 00 af e1 01 05 ba] (now have [a4 05 51 00 af e1 01 05 ba] in buffer)
Read data: [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] (now have [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] in buffer)
looking for matching message in deque([(None, 111, array('B', [32])), (0, 81, array('B', [175, 225, 1, 5]))])
 - response found (0, 81, array('B', [175, 225, 1, 5]))
packing 'D\x02\x13\x049\x05\x00\x00' in array('B', [68, 2, 19, 4, 57, 5, 0, 0]),<type 'array.array'>
send acknowledged data 0
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([])
 - could not find response matching <function match at 0x1072f6410>
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 4f 00 44 02 13 04 39 05 00 00 8f]
 - sent message from queue, <ant.base.Message 4f:[00 44 02 13 04 39 05 00 00] (s:a4, l:9, c:8f)>
Read data: [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] (now have [a4 09 4e 00 43 3c 00 03 db 05 01 00 40] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
Read data: [a4 03 40 00 01 02 e4] (now have [a4 03 40 00 01 02 e4] in buffer)
Got channel event, <ant.base.Message 40:[00 01 02] (s:a4, l:3, c:e4)>
looking for matching message in deque([(0, 1, array('B', [5])), (0, 1, array('B', [2]))])
 - response found (0, 1, array('B', [5]))
done sending acknowledged data 0
Write data: [a4 03 43 00 00 10 f4]
wait for message matching <function match at 0x1072f6410>
Read data: [a4 03 40 00 43 00 a4] (now have [a4 03 40 00 43 00 a4] in buffer)
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x1072f6410>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 67, array('B', [0]))])
 - response found (0, 67, array('B', [0]))
Write data: [a4 02 44 00 03 e1]
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function match at 0x1072f6410>
Read data: [a4 03 40 00 44 00 a3] (now have [a4 03 40 00 44 00 a3] in buffer)
looking for matching message in deque([(None, 111, array('B', [32])), (0, 68, array('B', [0]))])
 - response found (0, 68, array('B', [0]))
Write data: [a4 02 45 00 13 f0]
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(None, 111, array('B', [32]))])
Read data: [a4 03 40 00 45 00 a2] (now have [a4 03 40 00 45 00 a2] in buffer)
 - could not find response matching <function match at 0x1072f6410>
looking for matching message in deque([(None, 111, array('B', [32])), (0, 69, array('B', [0]))])
 - response found (0, 69, array('B', [0]))
Read data: [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] (now have [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] in buffer)
Auth layer
on authentication
send acknowledged data 0
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2]))])
 - could not find response matching <function match at 0x1072f6410>
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 4f 00 44 04 01 00 39 05 00 00 9f]
 - sent message from queue, <ant.base.Message 4f:[00 44 04 01 00 39 05 00 00] (s:a4, l:9, c:9f)>
Read data: [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] (now have [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [5]))
Read data: [a4 09 50 00 43 3c 03 03 39 05 00 00 be] (now have [a4 09 50 00 43 3c 03 03 39 05 00 00 be] in buffer)
done sending acknowledged data 0
Get command, t15, s0
Read data: [a4 09 50 20 44 84 00 0c af e1 b3 e8 04] (now have [a4 09 50 20 44 84 00 0c af e1 b3 e8 04] in buffer)
Read data: [a4 09 50 40 47 41 52 4d 49 4e 20 53 d0] (now have [a4 09 50 40 47 41 52 4d 49 4e 20 53 d0] in buffer)
Read data: [a4 09 50 e0 57 49 4d 00 00 00 00 00 4e] (now have [a4 09 50 e0 57 49 4d 00 00 00 00 00 4e] in buffer)
parsing data array('B', [68, 132, 0, 12, 175, 225, 179, 232, 71, 65, 82, 77, 73, 78, 32, 83, 87, 73, 77, 0, 0, 0, 0, 0])
loaded authfile: array('B', [169, 222, 10, 170, 20, 187, 146, 149])
serial GARMIN SWIM, 3904102831, array('B', [169, 222, 10, 170, 20, 187, 146, 149])
send burst transfer 0
Send burst transfer, chan 0, data array('B', [68, 4, 3, 8, 57, 5, 0, 0, 169, 222, 10, 170, 20, 187, 146, 149])
Send burst transfer, packet 0, seq 0, data array('B', [68, 4, 3, 8, 57, 5, 0, 0])
Send burst transfer, packet 1, seq 5, data array('B', [169, 222, 10, 170, 20, 187, 146, 149])
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2]))])
 - could not find response matching <function match at 0x1072f6410>
Read data: [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] (now have [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] in buffer)
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 50 00 44 04 03 08 39 05 00 00 8a]
 - sent message from queue, <ant.base.Message 50:[00 44 04 03 08 39 05 00 00] (s:a4, l:9, c:8a)>
Write data: [a4 09 50 a0 a9 de 0a aa 14 bb 92 95 22]
 - sent message from queue, <ant.base.Message 50:[a0 a9 de 0a aa 14 bb 92 95] (s:a4, l:9, c:22)>
Read data: [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] (now have [a4 09 4e 00 43 3c 01 03 39 05 00 00 a2] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 0a ec] (now have [a4 03 40 00 01 0a ec] in buffer)
Got channel event, <ant.base.Message 40:[00 01 0a] (s:a4, l:3, c:ec)>
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
Read data: [a4 09 50 00 43 3c 03 03 39 05 00 00 be] (now have [a4 09 50 00 43 3c 03 03 39 05 00 00 be] in buffer)
Read data: [a4 09 50 a0 44 84 01 00 af e1 b3 e8 89] (now have [a4 09 50 a0 44 84 01 00 af e1 b3 e8 89] in buffer)
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [10])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [10]))
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [5]))
done sending burst transfer 0
Get command, t15, s0
parsing data array('B', [68, 132, 1, 0, 175, 225, 179, 232])
Authenticated
packing '\x03\x00\x00\x01\xf5\xe880\xff\xff\xff\xff\x00\x00\x00\x00' in array('B', [3, 0, 0, 1, 245, 232, 56, 48, 255, 255, 255, 255, 0, 0, 0, 0]),<type 'array.array'>
packing 'D\n\xfe\xff\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' in array('B', [68, 10, 254, 255, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),<type 'array.array'>
send burst transfer 0
Send burst transfer, chan 0, data array('B', [68, 10, 254, 255, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Send burst transfer, packet 0, seq 0, data array('B', [68, 10, 254, 255, 16, 0, 0, 0])
Send burst transfer, packet 1, seq 5, data array('B', [0, 0, 0, 0, 0, 0, 0, 0])
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2]))])
 - could not find response matching <function match at 0x1072f6410>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 50 00 44 0a fe ff 10 00 00 00 a2]
 - sent message from queue, <ant.base.Message 50:[00 44 0a fe ff 10 00 00 00] (s:a4, l:9, c:a2)>
Write data: [a4 09 50 a0 00 00 00 00 00 00 00 00 5d]
 - sent message from queue, <ant.base.Message 50:[a0 00 00 00 00 00 00 00 00] (s:a4, l:9, c:5d)>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 0a ec] (now have [a4 03 40 00 01 0a ec] in buffer)
Got channel event, <ant.base.Message 40:[00 01 0a] (s:a4, l:3, c:ec)>
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
Read data: [a4 09 50 00 43 3c 03 03 39 05 00 00 be] (now have [a4 09 50 00 43 3c 03 03 39 05 00 00 be] in buffer)
Read data: [a4 09 50 20 44 8a 00 00 00 00 00 00 13] (now have [a4 09 50 20 44 8a 00 00 00 00 00 00 13] in buffer)
Read data: [a4 09 50 40 10 00 00 00 10 00 00 00 bd] (now have [a4 09 50 40 10 00 00 00 10 00 00 00 bd] in buffer)
Read data: [a4 09 50 e0 00 00 00 00 00 00 00 00 1d] (now have [a4 09 50 e0 00 00 00 00 00 00 00 00 1d] in buffer)
parsing data array('B', [68, 138, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [10])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [10]))
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [5]))
done sending burst transfer 0
Get command, t15, s1
send burst transfer 0
Send burst transfer, chan 0, data array('B', [68, 12, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 245, 232, 56, 48, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 229, 218])
Send burst transfer, packet 0, seq 0, data array('B', [68, 12, 0, 0, 0, 0, 0, 0])
Send burst transfer, packet 1, seq 1, data array('B', [3, 0, 0, 1, 245, 232, 56, 48])
Send burst transfer, packet 2, seq 2, data array('B', [255, 255, 255, 255, 0, 0, 0, 0])
Send burst transfer, packet 3, seq 7, data array('B', [0, 0, 0, 0, 0, 0, 229, 218])
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2]))])
 - could not find response matching <function match at 0x1072f6410>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 50 00 44 0c 00 00 00 00 00 00 b5]
 - sent message from queue, <ant.base.Message 50:[00 44 0c 00 00 00 00 00 00] (s:a4, l:9, c:b5)>
Write data: [a4 09 50 20 03 00 00 01 f5 e8 38 30 ca]
 - sent message from queue, <ant.base.Message 50:[20 03 00 00 01 f5 e8 38 30] (s:a4, l:9, c:ca)>
Write data: [a4 09 50 40 ff ff ff ff 00 00 00 00 bd]
 - sent message from queue, <ant.base.Message 50:[40 ff ff ff ff 00 00 00 00] (s:a4, l:9, c:bd)>
Write data: [a4 09 50 e0 00 00 00 00 00 00 e5 da 22]
 - sent message from queue, <ant.base.Message 50:[e0 00 00 00 00 00 00 e5 da] (s:a4, l:9, c:22)>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 0a ec] (now have [a4 03 40 00 01 0a ec] in buffer)
Got channel event, <ant.base.Message 40:[00 01 0a] (s:a4, l:3, c:ec)>
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
Read data: [a4 09 50 00 43 3c 03 03 39 05 00 00 be] (now have [a4 09 50 00 43 3c 03 03 39 05 00 00 be] in buffer)
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [10])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [10]))
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [5]))
done sending burst transfer 0
Get command, t15, s0
Read data: [a4 09 50 a0 44 8c 00 00 00 00 00 00 95] (now have [a4 09 50 a0 44 8c 00 00 00 00 00 00 95] in buffer)
parsing data array('B', [68, 140, 0, 0, 0, 0, 0, 0])
Download 65534, o0, c0
packing 'D\t\xfe\xff\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00' in array('B', [68, 9, 254, 255, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),<type 'array.array'>
send burst transfer 0
Send burst transfer, chan 0, data array('B', [68, 9, 254, 255, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
Send burst transfer, packet 0, seq 0, data array('B', [68, 9, 254, 255, 0, 0, 0, 0])
Send burst transfer, packet 1, seq 5, data array('B', [0, 1, 0, 0, 0, 0, 0, 0])
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2]))])
 - could not find response matching <function match at 0x1072f6410>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
Got broadcast data, examine queue to see if we should send anything back
Write data: [a4 09 50 00 44 09 fe ff 00 00 00 00 b1]
 - sent message from queue, <ant.base.Message 50:[00 44 09 fe ff 00 00 00 00] (s:a4, l:9, c:b1)>
Write data: [a4 09 50 a0 00 01 00 00 00 00 00 00 5c]
 - sent message from queue, <ant.base.Message 50:[a0 00 01 00 00 00 00 00 00] (s:a4, l:9, c:5c)>
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
No new data this period
Got broadcast data, examine queue to see if we should send anything back
 - no messages in queue
Read data: [a4 03 40 00 01 0a ec] (now have [a4 03 40 00 01 0a ec] in buffer)
Got channel event, <ant.base.Message 40:[00 01 0a] (s:a4, l:3, c:ec)>
Read data: [a4 03 40 00 01 05 e3] (now have [a4 03 40 00 01 05 e3] in buffer)
Got channel event, <ant.base.Message 40:[00 01 05] (s:a4, l:3, c:e3)>
Read data: [a4 09 50 00 43 3c 03 03 39 05 00 00 be] (now have [a4 09 50 00 43 3c 03 03 39 05 00 00 be] in buffer)
Read data: [a4 09 50 20 44 89 02 00 00 00 00 00 12] (now have [a4 09 50 20 44 89 02 00 00 00 00 00 12] in buffer)
Read data: [a4 09 50 c0 00 00 00 00 3b 7f fd cf 4b] (now have [a4 09 50 c0 00 00 00 00 3b 7f fd cf 4b] in buffer)
parsing data array('B', [68, 137, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 127, 253, 207])
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [10])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [10]))
wait for message matching <function match at 0x1072f6410>
looking for matching message in deque([(0, 1, array('B', [2])), (0, 1, array('B', [5]))])
 - response found (0, 1, array('B', [5]))
done sending burst transfer 0
Wait for response...
Get command, t15, s1
Run 5
Stoping ant.easy
Stoping ant.base
Read data: [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] (now have [a4 09 4e 00 43 3c 02 03 39 05 00 00 a1] in buffer)
Ant runner stopped
Traceback (most recent call last):
  File "build/bdist.macosx-10.8-intel/egg/antfs_cli/program.py", line 354, in main
    g.start()
  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 217, in start
    self._main()
  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 155, in _main
    self.on_transport(beacon)
  File "build/bdist.macosx-10.8-intel/egg/antfs_cli/program.py", line 196, in on_transport
    result = self.set_time()
  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 349, in set_time
    result = self._get_commandpipe()
  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 228, in _get_commandpipe
    return ant.fs.commandpipe.parse(self.download(0xfffe))
  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 331, in download
    response._get_argument("response"))
AntFSDownloadException: ('Download request failed: ', 2)
'Traceback (most recent call last):'
'  File "build/bdist.macosx-10.8-intel/egg/antfs_cli/program.py", line 354, in main'
'    g.start()'
'  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 217, in start'
'    self._main()'
'  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 155, in _main'
'    self.on_transport(beacon)'
'  File "build/bdist.macosx-10.8-intel/egg/antfs_cli/program.py", line 196, in on_transport'
'    result = self.set_time()'
'  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 349, in set_time'
'    result = self._get_commandpipe()'
'  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 228, in _get_commandpipe'
'    return ant.fs.commandpipe.parse(self.download(0xfffe))'
'  File "/Library/Python/2.7/site-packages/ant/fs/manager.py", line 331, in download'
'    response._get_argument("response"))'
"AntFSDownloadException: ('Download request failed: ', 2)"
```

Hope that helps to solve the bug.
Cheers

**Comment by Tigge** [comment]
At least for @metalinjection and @cork, I think this should fix the problem.

**Comment by cork** [comment]
Yes, that fixes the problem. Thanks for a great project!

**Comment by metalinjection** [comment]
Indeed it does work like a charm!!! Cheeers mate

**Comment by jbiblio** [comment]
Works for me, too. Thanks a lot!
