### ISSUE TITLE
DriverNotFound?

### ISSUE THREAD

**Issue by AjayTalati** [Tigge/antfs-cli#167]
Hi,

I've got a Garmin Vivoactive HR watch and I'm trying to get the `fit` files from the watch? 

I think I've got `antfs-cli` and `openant` properly installed, as I can get the help options,

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/Downloads/antfs-cli-master$ antfs-cli -h
usage: antfs-cli [-h] [--upload] [--debug] [--pair] [-a]

Extracts FIT files from ANT-FS based sport watches.

optional arguments:
  -h, --help           show this help message and exit
  --upload             enable uploading
  --debug              enable debug
  --pair               force pairing even if already paired
  -a, --skip-archived  don't download files marked as 'archived' on the watch
``` 

I'm stuck how to actually get the files from the watch? I tried,

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/Downloads/antfs-cli-master$ antfs-cli --upload
Driver available: [<class ant.base.driver.SerialDriver at 0x7fb1e8529600>, <class ant.base.driver.USB2Driver at 0x7fb1e8529a10>, <class ant.base.driver.USB3Driver at 0x7fb1e8529a78>]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 354, in main
    g = AntFSCLI(config_dir, args)
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 131, in __init__
    Application.__init__(self)
  File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 104, in __init__
    self._node = Node()
  File "/usr/local/lib/python2.7/dist-packages/ant/easy/node.py", line 56, in __init__
    self.ant = Ant()
  File "/usr/local/lib/python2.7/dist-packages/ant/base/ant.py", line 55, in __init__
    self._driver = find_driver()
  File "/usr/local/lib/python2.7/dist-packages/ant/base/driver.py", line 256, in find_driver
    raise DriverNotFound
DriverNotFound
Interrupted: 
```  

Any suggestion how to get this working please?

**Comment by yml** [comment]
Installing `pyserial` fixed this issue for me.

**Comment by AjayTalati** [comment]
Hi @yml thank you very much for the suggestion - I installed `pyserial` but I still get the same error?

```
(py35_pytorch) ajay@ajay-h8-1170uk:~$ pip install pyserial
Collecting pyserial
  Using cached pyserial-3.3-py2.py3-none-any.whl
Installing collected packages: pyserial
Successfully installed pyserial-3.3
(py35_pytorch) ajay@ajay-h8-1170uk:~/Downloads/antfs-cli-master$ antfs-cli --upload
Driver available: [<class ant.base.driver.SerialDriver at 0x7f9a9d9ed600>, <class ant.base.driver.USB2Driver at 0x7f9a9d9eda10>, <class ant.base.driver.USB3Driver at 0x7f9a9d9eda78>]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 354, in main
    g = AntFSCLI(config_dir, args)
  File "build/bdist.linux-x86_64/egg/antfs_cli/program.py", line 131, in __init__
    Application.__init__(self)
  File "/usr/local/lib/python2.7/dist-packages/ant/fs/manager.py", line 104, in __init__
    self._node = Node()
  File "/usr/local/lib/python2.7/dist-packages/ant/easy/node.py", line 56, in __init__
    self.ant = Ant()
  File "/usr/local/lib/python2.7/dist-packages/ant/base/ant.py", line 55, in __init__
    self._driver = find_driver()
  File "/usr/local/lib/python2.7/dist-packages/ant/base/driver.py", line 256, in find_driver
    raise DriverNotFound
DriverNotFound
Interrupted:

**Comment by terrydixon** [comment]
I have the exact same problem. Any suggestions?

**Comment by AjayTalati** [comment]
Nope sorry - I'm thinking of buying a new watch - any suggestions on one I can easily get data out of?
