### ISSUE TITLE
After upgrade to Ubuntu 20.10 the GFR610 is not found by antfs-cli (which it did before)

### ISSUE THREAD

**Issue by PLSchrier-1503** [Tigge/antfs-cli#185]
after upgrading to Ubuntu 20.10 I noticed that I had to reinstall the antfs-cli and openant. After doing so (as indicated in the READMEs), my Garmin ForeRunner610 is still not found anymore by the antfs.....

It starts searching but replies that the Message object does not contain data....I know I have seeen this some years ago, but I do not recollect how I solved it. 

I am using python3.8 on my machine.

Included the latest log-file:
[20201030-161421-antfs-cli.log](https://github.com/Tigge/antfs-cli/files/5465974/20201030-161421-antfs-cli.log)

Output to screen:
Driver available: [<class 'ant.base.driver.USB2Driver'>, <class 'ant.base.driver.USB3Driver'>]
 - Using: <class 'ant.base.driver.USB3Driver'>
Request basic information...
  Capabilities:  array('B', [8, 8, 0, 186, 54, 0, 223])
Starting system...
Key done...
Searching...
Exception in thread ant.base:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ant/base/ant.py", line 180, in _worker
    and message.data[1] == 0x01
AttributeError: 'Message' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/antfs_cli-0.4-py3.8.egg/antfs_cli/program.py", line 384, in main
    g.start()
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 223, in start
    self._main()
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 150, in _main
    if self.on_link(beacon):
  File "/usr/local/lib/python3.8/dist-packages/antfs_cli-0.4-py3.8.egg/antfs_cli/program.py", line 167, in on_link
    self.link()
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 383, in link
    self._send_command(LinkCommand(self._frequency, 4, self._serial_number))
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 199, in _send_command
    self._channel.send_acknowledged_data(data)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/channel.py", line 119, in send_acknowledged_data
    self.wait_for_event([Message.Code.EVENT_TRANSFER_TX_COMPLETED])
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/channel.py", line 50, in wait_for_event
    return wait_for_event(ok_codes, self._node._events, self._node._event_cond)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/filter.py", line 73, in wait_for_event
    return wait_for_message(match, process, queue, condition)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/filter.py", line 62, in wait_for_message
    raise AntException("Timed out while waiting for message")
ant.easy.exception.AntException: Timed out while waiting for message
Interrupted: Timed out while waiting for message

**EDIT:**
I researcjhed a bit further: the moment the abtfs-cli command outputs 'Searching...', the ttyUSB0 device is removed and unbound

Any ideas?

Kind regards
Peter

**Comment by awatersonpersonal** [comment]
Is there any update on this I m having the same issue on debian (raspberry pi).

**Comment by PLSchrier** [comment]
This was solved by newest version of openant (as mentioned in this issue: https://github.com/Tigge/antfs-cli/issues/186)
