### ISSUE TITLE
Neither XDG_CONFIG_HOME nor HOME found in the environment

### ISSUE THREAD

**Issue by tdpo2** [Tigge/antfs-cli#193]
C:\Users\username>antfs-cli
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\Scripts\antfs-cli-script.py", line 33, in <module>
    sys.exit(load_entry_point('antfs-cli==0.4', 'console_scripts', 'antfs-cli')())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\antfs_cli-0.4-py3.8.egg\antfs_cli\program.py", line 354, in main
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\antfs_cli-0.4-py3.8.egg\antfs_cli\utilities.py", line 60, in get_config_dir
antfs_cli.utilities.XDGError: Neither XDG_CONFIG_HOME nor HOME found in the environment

**Comment by gjaekel** [comment]
From the prompt, this is no Unix/Linux environment. You're using plain Windows or a WSL?

I would say that `antfs-cli` expect at least `HOME` because it store the configuration and downloaded data at `~/.config/antfs-cli` .

**Comment by tdpo2** [comment]
Windows.

**Comment by tdpo2** [comment]
I used alternative from https://www.dcrainmaker.com/2011/10/garmin-forerunner-910xt-in-depth-review.html

I used ANT agent.
