### ISSUE TITLE
Timed out while waiting for message

### ISSUE THREAD

**Issue by janjezik** [Tigge/antfs-cli#194]
Hi.
Thanks for sharing antfs-cli with the world.
I have been using it for years on old debian with no issues. Recently i switched to Ubuntu 22.04.1 and I am now unable to make it work. I have read all the relevant issues related to "timeout" in antfs-cli as well as in openant. I have tried everything I was able to understand:

- I have tried it after removing the authfile from ~/.config/antfs-cli/xxxxxxxxxx/
- I have also tried to remove the whole ~/.config/antfs-cli/ directory
- I have tried the old version of antfs-cli and openant I had been using on debian
- I have tried the most recent versions of antfs-cli and openant
- I checked if the ANT dongle is recognized - it is: `Bus 003 Device 002: ID 0fcf:1009 Dynastream Innovations, Inc. ANTUSB-m Stick`

After I run antfs-cli I only get
`Request basic information...`

After couple of seconds it fails with
`ant.easy.exception.AntException: Timed out while waiting for message`

The ANT probably doesn't even start any communication with my Garmin Swim watch, because it doesn't show anything on the display.

Debug log: [20230205-162321-antfs-cli-log](https://gist.github.com/janjezik/4ac77bb85fe30d79478de75455a172d8#file-20230205-162321-antfs-cli-log)
Terminal output: https://gist.github.com/janjezik/0873c673389395c45b01e8dcca180823#file-terminal-output
I am using Python 3.10

I appreciate any suggestion how to debug this issue.
Thanks

**Comment by gjaekel** [comment]
> * I have tried it after removing the authfile from ~/.config/antfs-cli/xxxxxxxxxx/
> * I have also tried to remove the whole ~/.config/antfs-cli/ directory

Did you also try to re-pair (after enabling pairing on the watch)?

Do you need a log of a working transfer to compare? I may provide one.

BTW: Should make no big deal because it have worked before, but just for interest: What model of watch?

**Comment by janjezik** [comment]
Hi.
The watch is Garmin Swim.
Trying to pair fails as well:
[Terminal output](https://gist.github.com/janjezik/663b780e49d61dcc934ecb8bbe201397#file-antfs-cli-pair-terminal-output)


Debug log from the pairing attempt:
[20230205-222343-antfs-cli.log](https://gist.github.com/janjezik/785f42dee6c0fa020af899a638547d13#file-20230205-222343-antfs-cli-log)

**Comment by janjezik** [comment]
Hi.
I am still unable to make it work.

> Do you need a log of a working transfer to compare? I may provide one.

Could you please provide me with the debug log from successful transfer?

Thank you.

**Comment by gjaekel** [comment]
I would like to send it private to you, may contact me via email?

**Comment by alelova** [comment]
Hello.
Same issue after update ubuntu to 22.04.

**Comment by gotenp** [comment]
I have the same issue since I upgraded to linux mint 21.1 from 20.3
Is there a way to get antfs-cli working again.
I noticed that openant scan seems to be working
This is the output:
`openant scan 
Starting scanner for #0, type 0, press Ctrl-C to finish
Found new device #37494 DeviceType.Unknown; device_type: 1, transmission_type: 5
`
But using antfs-cli gives
`antfs-cli 
Request basic information...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg/antfs_cli/program.py", line 382, in main
    g = AntFSCLI(config_dir, args)
  File "/usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg/antfs_cli/program.py", line 140, in __init__
    Application.__init__(self)
  File "/home/peter/.local/lib/python3.10/site-packages/ant/fs/manager.py", line 141, in __init__
    raise e
  File "/home/peter/.local/lib/python3.10/site-packages/ant/fs/manager.py", line 115, in __init__
    m = self._node.request_message(Message.ID.RESPONSE_CAPABILITIES)
  File "/home/peter/.local/lib/python3.10/site-packages/ant/easy/node.py", line 116, in request_message
    return self.wait_for_special(messageId)
  File "/home/peter/.local/lib/python3.10/site-packages/ant/easy/node.py", line 144, in wait_for_special
    return wait_for_special(event_id, self._responses, self._responses_cond)
  File "/home/peter/.local/lib/python3.10/site-packages/ant/easy/filter.py", line 111, in wait_for_special
    return wait_for_message(match, process, queue, condition)
  File "/home/peter/.local/lib/python3.10/site-packages/ant/easy/filter.py", line 62, in wait_for_message
    raise AntException("Timed out while waiting for message")
ant.easy.exception.AntException: Timed out while waiting for message
Interrupted: Timed out while waiting for message
`
if I use --debug I get this info...
`Drivers available: [<class 'ant.base.driver.SerialDriver'>, <class 'ant.base.driver.USB2Driver'>, <class 'ant.base.driver.USB3Driver'>]
Using driver: <class 'ant.base.driver.USB2Driver'>
USB Find device, vendor 0xfcf, product 0x1008
USB Config values:
 Config 1
  Interface 0, Alt 0
   Endpoint 129
   Endpoint 1
A kernel driver active, detatching
USB Endpoint out:       ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1, 1
USB Endpoint in:       ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1, 129
Ant runner started
Write data: [a4 01 4a 00 ef]
Read data: [a4 01 6f 20 ea] (now have [a4 01 6f 20 ea] in buffer)
Got response start-up, <ant.base.Message 6f:[20] (s:a4, l:1, c:ea)>
Timeout waiting for message: (110, 'Operation timed out')
Write data: [a4 02 4d 00 54 bf]
Read data: [a4 06 54 08 03 00 ba 36 00 71] (now have [a4 06 54 08 03 00 ba 36 00 71] in buffer)
Write data: [a4 09 46 00 a8 a4 23 b9 f5 5e 63 c1 74]
Write data: [a4 02 4d 00 61 8a]
Got response general, <ant.base.Message 54:[08 03 00 ba 36 00] (s:a4, l:6, c:71)>
wait for message matching <function wait_for_response.<locals>.match at 0x7f8db5fa5090>
Write data: [a4 02 4d 00 3e d5]
looking for matching message in deque([])
Read data: [a4 03 40 00 46 00 a1] (now have [a4 03 40 00 46 00 a1] in buffer)
_worker_response None, 111, array('B', [32])
 - could not find response matching <function wait_for_response.<locals>.match at 0x7f8db5fa5090>
Got channel response other, <ant.base.Message 40:[00 46 00] (s:a4, l:3, c:a1)>
_worker_response None, 84, array('B', [8, 3, 0, 186, 54, 0])
capabilities max_channels: 8, max_networks 3, standard_options: set(), advanced_options: {<AdvancedOptions.Reserved: 8>, <AdvancedOptions.SerialNumberEnabled: 3>, <AdvancedOptions.LowPrioritySearchNEnabled: 5>, <AdvancedOptions.SearchListEnabled: 7>, <AdvancedOptions.PerChannelTxPowerEnabled: 4>}; {<AdvancedOptionsTwo.ExtMessageEnabled: 1>, <AdvancedOptionsTwo.ExtAssignEnabled: 5>, <AdvancedOptionsTwo.ScanModeEnabled: 2>, <AdvancedOptionsTwo.ProximitySearchEnabled: 4>}
_worker_response 0, 70, array('B', [0])
looking for matching message in deque([(None, 111, array('B', [32])), (0, 70, array('B', [0]))])
 - response found (0, 70, array('B', [0]))
Request basic information...
requesting message 0x54
Read data: [a4 04 61 02 39 30 00 ca a4 0b 3e 41 4a 4b 31 2e 30 34 52 41 46 00 9f] (now have [a4 04 61 02 39 30 00 ca a4 0b 3e 41 4a 4b 31 2e 30 34 52 41 46 00 9f] in buffer)
Write data: [a4 02 4d 00 54 bf]
Got response general, <ant.base.Message 61:[02 39 30 00] (s:a4, l:4, c:ca)>
done requesting message 0x54
Got response general, <ant.base.Message 3e:[41 4a 4b 31 2e 30 34 52 41 46 00] (s:a4, l:11, c:9f)>
_worker_response None, 97, array('B', [2, 57, 48, 0])
wait for message matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Read data: [a4 06 54 08 03 00 ba 36 00 71] (now have [a4 06 54 08 03 00 ba 36 00 71] in buffer)
serial 3160322
looking for matching message in deque([(None, 111, array('B', [32]))])
Got response general, <ant.base.Message 54:[08 03 00 ba 36 00] (s:a4, l:6, c:71)>
_worker_response None, 62, array('B', [65, 74, 75, 49, 46, 48, 52, 82, 65, 70, 0])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
ant_version AJK1.04RAF
_worker_response None, 84, array('B', [8, 3, 0, 186, 54, 0])
capabilities max_channels: 8, max_networks 3, standard_options: set(), advanced_options: {<AdvancedOptions.Reserved: 8>, <AdvancedOptions.SerialNumberEnabled: 3>, <AdvancedOptions.LowPrioritySearchNEnabled: 5>, <AdvancedOptions.SearchListEnabled: 7>, <AdvancedOptions.PerChannelTxPowerEnabled: 4>}; {<AdvancedOptionsTwo.ExtMessageEnabled: 1>, <AdvancedOptionsTwo.ExtAssignEnabled: 5>, <AdvancedOptionsTwo.ScanModeEnabled: 2>, <AdvancedOptionsTwo.ProximitySearchEnabled: 4>}
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
looking for matching message in deque([(None, 111, array('B', [32]))])
 - could not find response matching <function wait_for_special.<locals>.match at 0x7f8db5fa51b0>
Timeout waiting for message: (110, 'Operation timed out')
Stoping openant.easy
Stoping openant.base
Timeout waiting for message: (110, 'Operation timed out')
Ant runner stopped
usbdriver.closed
`

**Comment by gotenp** [comment]
> I have the same issue since I upgraded to linux mint 21.1 from 20.3 Is there a way to get antfs-cli working again. I noticed that openant scan seems to be working This is the output: 

SNIP
>

Update: I reverted back to mint 20.3 antfs-cli is working again ... Happy days... :-)

**Comment by prcoder-1** [comment]
Same issue (Timed out while waiting for message) on Fedora release 37 (Thirty Seven).
Before that it worked fine on Fedora 35.

**Comment by microniko** [comment]
I have the same issue with Debian GNU/Linux 11 (bullseye, kernel 5.10.0-23-amd64).

**Comment by microniko** [comment]
I have the same issue with Debian GNU/Linux 12.1 (bookworm, kernel 6.1.0-10-amd64)

```
(antfs) nicolas@carbone:~/openant-master$ antfs-cli --pair
Request basic information...
Traceback (most recent call last):
  File "/home/nicolas/antfs/lib/python3.11/site-packages/antfs_cli-0.4-py3.11.egg/antfs_cli/program.py", line 382, in main
    g = AntFSCLI(config_dir, args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/antfs/lib/python3.11/site-packages/antfs_cli-0.4-py3.11.egg/antfs_cli/program.py", line 140, in __init__
    Application.__init__(self)
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/fs/manager.py", line 141, in __init__
    raise e
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/fs/manager.py", line 115, in __init__
    m = self._node.request_message(Message.ID.RESPONSE_CAPABILITIES)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/easy/node.py", line 116, in request_message
    return self.wait_for_special(messageId)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/easy/node.py", line 144, in wait_for_special
    return wait_for_special(event_id, self._responses, self._responses_cond)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/easy/filter.py", line 111, in wait_for_special
    return wait_for_message(match, process, queue, condition)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/antfs/lib/python3.11/site-packages/ant/easy/filter.py", line 62, in wait_for_message
    raise AntException("Timed out while waiting for message")
ant.easy.exception.AntException: Timed out while waiting for message
Interrupted: Timed out while waiting for message
```

**Comment by arjanboltjes** [comment]
First time user here.
Same issue, with an identical output from `antfs-cli --pair` as @microniko got.
I'm not sure `openant scan` yields any pairing, like @gotenp posted: how long is this pairing supposed to take? I haven't seen the 'Found new device' myself.

Garmin 310 XT, pairing enabled
Ubuntu 22.04.2 LTS
openant 1.2.1
antfs-cli downloaded just now

**Comment by microniko** [comment]
I tried with Linux Mint 20.3 Una (like @gotenp) in a VirtualBox VM but I had the same error :

```
vboxuser@linuxmint:~/garmin/antfs-cli-master$ antfs-cli --pair
Request basic information...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/antfs_cli-0.4-py3.8.egg/antfs_cli/program.py", line 382, in main
    g = AntFSCLI(config_dir, args)
  File "/usr/local/lib/python3.8/dist-packages/antfs_cli-0.4-py3.8.egg/antfs_cli/program.py", line 140, in __init__
    Application.__init__(self)
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 141, in __init__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/ant/fs/manager.py", line 115, in __init__
    m = self._node.request_message(Message.ID.RESPONSE_CAPABILITIES)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/node.py", line 116, in request_message
    return self.wait_for_special(messageId)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/node.py", line 144, in wait_for_special
    return wait_for_special(event_id, self._responses, self._responses_cond)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/filter.py", line 111, in wait_for_special
    return wait_for_message(match, process, queue, condition)
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/filter.py", line 62, in wait_for_message
    raise AntException("Timed out while waiting for message")
ant.easy.exception.AntException: Timed out while waiting for message
Interrupted: Timed out while waiting for message
```

I had a Cycplus ANT stick :
```
Bus 002 Device 004: ID 0fcf:1008 Dynastream Innovations, Inc. ANTUSB2 Stick
```

Will I try with Fedora 35 like @prcoder-1 ?
*edit* : same error message...

**Comment by microniko** [comment]
@arjanboltjes and @prcoder-1  : do you finally solved the problem ?

**Comment by alelova** [comment]
cool! it works in Ubuntu 22.04 after the openant update. thanks @tuna-f1sh, i can still use my garmin from 2012.
```
m:~/varios/openant/openant$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

m:~/varios/openant/openant$ openant --version
openant 1.3.1

m:~/varios/openant/openant$ antfs-cli
Searching...
Authenticating with Forerunner 310XT (3894335436)
 - Passkey: OK
 - Set time: FAILED
Downloading 0 file(s)

```

**Comment by arjanboltjes** [comment]
> [@arjanboltjes](https://github.com/arjanboltjes) and [@prcoder-1](https://github.com/prcoder-1) : do you finally solved the problem ?

@microniko No, I gave up back them. I recently returned to this, tried, failed again, found my comment above that I had forgotten about. I then noticed that @alelova had a newer version of openant: I removed openant since it wouldn't automatically write over it, installed it again, still got the old version, but then ran `pip install openant==1.3.2` to force install the newest, and this worked:

```
$ openant --version
openant 1.3.2
```

Still, running openant as described on the GitHub doesn't yield me anything. Empty json file, no devices found.
I noticed one line on the openant GitHub page that I'm not sure how to interpret, though: "If using on Linux, a udev rule for the Dynastream ANTUSB stick can be installed with `sudo python -m openant.udev_rules`." This yields "/usr/bin/python: No module named openant.udev_rules".

When I, regardless install antfs-cli by running `sudo python setup.py install`, I'm getting:

```
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing antfs_cli.egg-info/PKG-INFO
writing dependency_links to antfs_cli.egg-info/dependency_links.txt
writing entry points to antfs_cli.egg-info/entry_points.txt
writing requirements to antfs_cli.egg-info/requires.txt
writing top-level names to antfs_cli.egg-info/top_level.txt
reading manifest file 'antfs_cli.egg-info/SOURCES.txt'
adding license file 'LICENCE'
writing manifest file 'antfs_cli.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/program.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/scripting.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/utilities.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/__init__.py -> build/bdist.linux-x86_64/egg/antfs_cli
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/program.py to program.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/scripting.py to scripting.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/utilities.py to utilities.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/__init__.py to __init__.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/antfs_cli-0.4-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing antfs_cli-0.4-py3.10.egg
Removing /usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg
Copying antfs_cli-0.4-py3.10.egg to /usr/local/lib/python3.10/dist-packages
antfs-cli 0.4 is already the active version in easy-install.pth
Installing antfs-cli script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Processing dependencies for antfs-cli==0.4
Searching for openant==1.2.1
Best match: openant 1.2.1
Adding openant 1.2.1 to easy-install.pth file
Installing openant script to /usr/local/bin

Using /usr/local/lib/python3.10/dist-packages
Searching for pyusb==1.2.1
Best match: pyusb 1.2.1
Processing pyusb-1.2.1-py3.10.egg
pyusb 1.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.10/dist-packages/pyusb-1.2.1-py3.10.egg
Finished processing dependencies for antfs-cli==0.4
```

What strikes me here is that openant 1.2.1 is found. So, despite upgrading to 1.3.2, antfs-cli does not seem to find it or use it?

If I then try to run `antfs-cli` I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/antfs-cli", line 33, in <module>
    sys.exit(load_entry_point('antfs-cli==0.4', 'console_scripts', 'antfs-cli')())
  File "/usr/local/bin/antfs-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg/antfs_cli/program.py", line 34, in <module>
ModuleNotFoundError: No module named 'ant'
```

So, new errors that I see is the same as the issue mentioned here: https://github.com/Tigge/antfs-cli/issues/195
If I for instance install `ant` via pip, I get the next issue: `ModuleNotFoundError: No module named 'ant.fs.manager'`.

Here I get the impression that openant was not installed properly after all, since both ant.py (in base) and manager.py (in fs) are part of openant, and antfs-cli can't find these. Although I may be completely mistaken.

All in all, not working still - for me, that is.
