### ISSUE TITLE
installation of antfs-cli failed - error in py library reference

### ISSUE THREAD

**Issue by okvittem** [Tigge/antfs-cli#195]
Hi, antfs-cli installation seems to fail, mixing up library directories and distribution package.
I have python 3.10 and latest antfs-cli from github
when starting antfs-cli I get this error message that seem to try to use a distribution package (antfs_cli-0.4-py3.10.egg) as library reference...

```
sudo pip install openant
sudo python setup.py install

~/sw/Garmin-Forerunner-610-Extractor> antfs-cli 
Traceback (most recent call last):
  File "/usr/local/bin/antfs-cli", line 33, in <module>
    sys.exit(load_entry_point('antfs-cli==0.4', 'console_scripts', 'antfs-cli')())
  File "/usr/local/bin/antfs-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg/antfs_cli/program.py", line 34, in <module>
ModuleNotFoundError: No module named 'ant'

```

**Comment by okvittem** [comment]
Here is the installation log : 
```
~/sw/Garmin-Forerunner-610-Extractor> sudo python setup.py install
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing antfs_cli.egg-info/PKG-INFO
writing dependency_links to antfs_cli.egg-info/dependency_links.txt
writing entry points to antfs_cli.egg-info/entry_points.txt
writing requirements to antfs_cli.egg-info/requires.txt
writing top-level names to antfs_cli.egg-info/top_level.txt
reading manifest file 'antfs_cli.egg-info/SOURCES.txt'
adding license file 'LICENCE'
writing manifest file 'antfs_cli.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/scripting.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/utilities.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/__init__.py -> build/bdist.linux-x86_64/egg/antfs_cli
copying build/lib/antfs_cli/program.py -> build/bdist.linux-x86_64/egg/antfs_cli
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/scripting.py to scripting.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/utilities.py to utilities.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/antfs_cli/program.py to program.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antfs_cli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/antfs_cli-0.4-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing antfs_cli-0.4-py3.10.egg
Removing /usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg
Copying antfs_cli-0.4-py3.10.egg to /usr/local/lib/python3.10/dist-packages
antfs-cli 0.4 is already the active version in easy-install.pth
Installing antfs-cli script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/antfs_cli-0.4-py3.10.egg
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Processing dependencies for antfs-cli==0.4
Searching for openant==1.3.2
Best match: openant 1.3.2
Adding openant 1.3.2 to easy-install.pth file
Installing openant script to /usr/local/bin

Using /usr/local/lib/python3.10/dist-packages
Searching for pyusb==1.2.1
Best match: pyusb 1.2.1
Adding pyusb 1.2.1 to easy-install.pth file

Using /usr/local/lib/python3.10/dist-packages
Finished processing dependencies for antfs-cli==0.4

```
